### PR TITLE
fix: dob cover render error

### LINKED ISSUE #868: Fallback image of DOB will be dismissed when the resource is not loaded
**Describe the bug**

https://github.com/user-attachments/assets/f3411cf1-bae4-41fc-ab98-7353c1ab5e8f

**To Reproduce**
https://testnet.explorer.nervos.org/nft-collections/0x8597a9aa15faf36dab42e05159e77d03bcec7d1f2a949590e9c0b77d548e74c2?tab=inventory

**Expected behavior**
Fallback image of DOB is displayed when the image resource is not loaded.

### LINKED ISSUE #885: Some DOB image don't  display  normally.
- As shown both in [DOB detail](https://explorer.nervos.org/nft-collections/0xabc42e9d8f631fe7d372a5e9880f2ba8b7a1eb55a877360c3337e4dc0b8e8e14) and related transaction page, some DOB image don't display normallyImage

- For some DOB, its tooltip is abnormal thought it has image on DOB detail page.Image

### PR DESCRIPTION
**Pull request by PainterPuppets**
fix: https://github.com/Magickbase/ckb-explorer-public-issues/issues/885
fix: https://github.com/Magickbase/ckb-explorer-public-issues/issues/868

before:
image

after:
image

### CODE REVIEW

File: src/utils/spore.ts [hunk 1]
```diff
@@ -74,9 +74,9 @@ export function parseSporeCellData(hexData: string) {
  * data: cell data
  * id: cell.type_script.args
  */
-export const getSporeImg = async ({ data: hexData, id: sporeId }: { data: string; id: string }): Promise<string> => {
+export const getSporeImg = async ({ data: hexData, id: sporeId }: { data?: string; id?: string }): Promise<string> => {
   const DEFAULT_URL = '/images/spore_placeholder.svg'
-  if (!hexData && !sporeId) {
+  if (!hexData || !sporeId) {
```
Comment (Keith-CY) [inline src/utils/spore.ts]: When `hex data` is non-null, image will be resolved from the data
When `sporeId` is non-null, image will be fetched from a dob service

So the condition should not be changed.

**Review by Keith-CY — APPROVED** [review]
